export const FETCH_WHISKIES = 'FETCH_WHISKIES'
export const FETCH_FILTERS = 'FETCH_FILTERS'
export const FETCH_PROFILES = 'FETCH_PROFILES'
export const FETCH_SORTERS = 'FETCH_SORTERS'

export const UPDATE_ACTIVE_FILTERS = 'UPDATE_ACTIVE_FILTERS'
export const UPDATE_ACTIVE_PROFILES = 'UPDATE_ACTIVE_PROFILES'
export const UPDATE_ACTIVE_SORTER = 'UPDATE_ACTIVE_SORTER'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
